baseurl: https://www.andrewhowden.com/
languageCode: en-us

title: Andrew Howden

buildDrafts: true

social:
  twitter: andrewhowdencom
  facebook: andrewhowdencom
  github: andrewhowdencom

menu:
  main:
    - Name: "Home"
      URL: "https://andrewhowden.com"

copyright: "Â© Andrew Howden, 2016"

Params:
  Gtm:
    Id: "GTM-KXPWKD"
  Css:
    Styles: "1460544193"
