baseurl: https://www.andrewhowden.com/
languageCode: en-us

title: andrewhowden.com

buildDrafts: true

social:
  twitter: andrewhowdencom
  facebook: andrewhowdencom
  github: andrewhowdencom

menu:
  main:
    - Name: "andrewhowden.com"
      URL: "https://andrewhowden.com"

copyright: "Â© Andrew Howden, 2016"
